# Generated by Django 4.0.4 on 2022-05-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_empleado_nombre_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
    ]
