# Generated by Django 4.0.4 on 2022-05-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=50, null=True, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Estatu',
                'verbose_name_plural': 'Estatus',
                'ordering': ['estatus'],
            },
        ),
        migrations.CreateModel(
            name='ProductosCrear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, unique=True, verbose_name='Nombre')),
                ('producto_pedido', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
