# Generated by Django 4.0.4 on 2022-05-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_productoscrear_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225, unique=True, verbose_name='Nombre')),
                ('producto_pedido', models.PositiveIntegerField()),
                ('prodcuto_enviado', models.PositiveIntegerField()),
                ('produto_entregado', models.PositiveIntegerField()),
                ('estado', models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='ordenes.estatus')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='ProductosCrear',
        ),
    ]
