# Generated by Django 4.0.4 on 2022-05-16 17:09

from django.db import migrations, models
from django.utils.timezone import utc
import datetime



class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_productos_delete_productoscrear'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 4, 15, 33, 41, 232741, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
