# Generated by Django 4.0.4 on 2022-05-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_alter_productos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatus',
            options={'ordering': ['id'], 'verbose_name': 'Estatu', 'verbose_name_plural': 'Estatus'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
