# Generated by Django 4.0.4 on 2022-05-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_alter_estatus_options_alter_productos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='prodcuto_enviado',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='produto_entregado',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
