# Generated by Django 4.0.4 on 2022-05-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_alter_productos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='producto_pedido',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='produto_entregado',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
